WARNING: dropped 300 NaN rows.
num_rows_f=0.000000, training=0, test=0

Running ML for column "surgery"
Running ML algos for input dataset "datasets/from_FD_paper/horses.csv"
Traceback (most recent call last):
  File "run_ml_algos.py", line 457, in <module>
    run_ml_for_all_columns(df, dataset_name, args.should_use_SFS)
  File "run_ml_algos.py", line 414, in run_ml_for_all_columns
    scaled_df = get_scaled_dataframe(training_df)
  File "run_ml_algos.py", line 128, in get_scaled_dataframe
    x_scaled = scaler.fit_transform(x)
  File "/home/ubuntu/x2/local/lib/python2.7/site-packages/sklearn/base.py", line 494, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/ubuntu/x2/local/lib/python2.7/site-packages/sklearn/preprocessing/data.py", line 292, in fit
    return self.partial_fit(X, y)
  File "/home/ubuntu/x2/local/lib/python2.7/site-packages/sklearn/preprocessing/data.py", line 318, in partial_fit
    estimator=self, dtype=FLOAT_DTYPES)
  File "/home/ubuntu/x2/local/lib/python2.7/site-packages/sklearn/utils/validation.py", line 416, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 29)) while a minimum of 1 is required by MinMaxScaler.
1 loops, best of 1: 657 msec per loop
